Repository ch3nkula/python-mentorship, pull requests merged in 2018-07, with the labels that each got.

#9 exercise_1.12.1
  Ruth/Chapter 1/exercise_1.12.1
Labels: good first issue

#7 excercise_1.12.1
  Tessy/Chapter_1/exercise_1.12.1
Labels: good first issue

#15 exercise_1.12.1
  Ifeanyi/Chapter_1/exercise_1.12.1
  Ifeanyi/README.md
  README.md
Labels: good first issue

#23 Using double quotes in Python.
  Tessy/Chapter_1/exercise_1.12.4
Labels: great-work

#20 Strings in double quotation marks display
  Ruth/Chapter_1/exercise_1.12.4
Labels: enhancement, great-work, help wanted

#27 Exercise on run-time errors.
  Ruth/Chapter_1/exercise_1.12.5
Labels: excellent-submission, great-work

#29 exercise_1.12.4
  Ifeanyi/Chapter_1/exercise_1.12.4
Labels: great-work

#30 How expressions are evaluated on the Python script.
  Ruth/Chapter_1/display_eval.py
  Ruth/Chapter_1/exercise_1.12.6
Labels: enhancement, great-work

#33 exercise_1.12.6
  Ifeanyi/Chapter_1/display_eval.py
  Ifeanyi/Chapter_1/exercise_1.12.6
Labels: great-work

#34 Exercise showing results of expressions typed at the prompt are automatically displayed while in script mode, the print function has to be used to evaluate the expression.
  Tessy/Chapter_1/display_eval.py
  Tessy/Chapter_1/exercise_1.12.6
Labels: enhancement, help wanted
